version: 2
updates:
  - package-ecosystem: docker
    directories:
      - "/8.2"
      - "/8.3"
      - "/8.4"
      - "/8.5"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
